version: "2"
linters:
  enable:
    - staticcheck
    - errcheck
    - govet
    - unused
    - gocritic
    - revive
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: exported
          disabled: true
